export const SNEAKERS = [
    {   id:1,
        image: '/img/sneakers/1.jpg',
        name: 'Мужские Кроссовки Nike Blazer Mid Suede',
        price: 12999,
        description: "Блейзеры бывают не только в коже. Данная модель из подлинейки Nike Suede, выполнены из мягкой, приятной на ощупь замши. Фирменный логотип Найк, в свою очередь, сделан из кожи. Кенды достаточно универсальны в носке. Подойдут и парням и девушкам.",
    },
    {
        id:2,
        image: '/img/sneakers/2.jpg',
        name: 'Мужские Кроссовки Nike Air Max 270',
        price: 12999,
    },
    {
        id:3,
        image: '/img/sneakers/3.jpg',
        name: 'Мужские Кроссовки Nike Blazer Mid Suede',
        price: 8499,
    },
    {
        id:4,
        image: '/img/sneakers/4.jpg',
        name: 'Кроссовки Puma X Aka Boku Future Rider',
        price: 8999,
    },
    {
        id:5,
        image: '/img/sneakers/5.jpg',
        name: 'Мужские Кроссовки Under Armour Curry 8',
        price: 8999,
    },
    {
        id:6,
        image: '/img/sneakers/6.jpg',
        name: 'Мужские Кроссовки Nike Kyrie 7',
        price: 11299,
    },
    {
        id:7,
        image: '/img/sneakers/7.jpg',
        name: 'Мужские Кроссовки Jordan Air Jordan 11',
        price: 10799,
    },
    {
        id:8,
        image: '/img/sneakers/8.jpg',
        name: 'Мужские Кроссовки Nike LeBron XVIII',
        price: 16499,
    },
    {
        id:9,
        image: '/img/sneakers/9.jpg',
        name: 'Мужские Кроссовки Nike Lebron XVIII Low',
        price: 13999,
    },
    {
        id:10,
        image: '/img/sneakers/10.jpg',
        name: 'Мужские Кроссовки Nike Blazer Mid Suede',
        price: 8499,
    },
    {
        id:11,
        image: '/img/sneakers/1.jpg',
        name: 'Кроссовки Puma X Aka Boku Future Rider',
        price: 8499,
    },
    {
        id:12,
        image: '/img/sneakers/1.jpg',
        name: 'Мужские Кроссовки Nike Kyrie Flytrap IV',
        price: 11299,
    },
]